server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sunggil2005!
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update

  graphql:
    schema:
      file-extensions: .graphqls
      locations: classpath:graphql/**/
    graphiql:
      enabled: true
      printer:
        enabled: true
